// Code generated by protoc-gen-go.
// source: baluba.proto
// DO NOT EDIT!

/*
Package baluba is a generated protocol buffer package.

It is generated from these files:
	baluba.proto

It has these top-level messages:
	Chunk
	Files
	UploadStatus
*/
package baluba

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UploadStatusCode int32

const (
	UploadStatusCode_Unknown UploadStatusCode = 0
	UploadStatusCode_Ok      UploadStatusCode = 1
	UploadStatusCode_Failed  UploadStatusCode = 2
)

var UploadStatusCode_name = map[int32]string{
	0: "Unknown",
	1: "Ok",
	2: "Failed",
}
var UploadStatusCode_value = map[string]int32{
	"Unknown": 0,
	"Ok":      1,
	"Failed":  2,
}

func (x UploadStatusCode) String() string {
	return proto.EnumName(UploadStatusCode_name, int32(x))
}
func (UploadStatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Chunk struct {
	Content   []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Hostname  string `protobuf:"bytes,3,opt,name=hostname" json:"hostname,omitempty"`
	Directory string `protobuf:"bytes,4,opt,name=directory" json:"directory,omitempty"`
	Size      int64  `protobuf:"varint,5,opt,name=size" json:"size,omitempty"`
	Version   int32  `protobuf:"varint,6,opt,name=version" json:"version,omitempty"`
	Action    string `protobuf:"bytes,7,opt,name=action" json:"action,omitempty"`
	Hash      string `protobuf:"bytes,8,opt,name=hash" json:"hash,omitempty"`
}

func (m *Chunk) Reset()                    { *m = Chunk{} }
func (m *Chunk) String() string            { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()               {}
func (*Chunk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Chunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Chunk) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Chunk) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Chunk) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

func (m *Chunk) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Chunk) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Chunk) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Chunk) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Files struct {
	File []*Chunk `protobuf:"bytes,1,rep,name=file" json:"file,omitempty"`
}

func (m *Files) Reset()                    { *m = Files{} }
func (m *Files) String() string            { return proto.CompactTextString(m) }
func (*Files) ProtoMessage()               {}
func (*Files) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Files) GetFile() []*Chunk {
	if m != nil {
		return m.File
	}
	return nil
}

type UploadStatus struct {
	Message  string           `protobuf:"bytes,1,opt,name=Message,json=message" json:"Message,omitempty"`
	Code     UploadStatusCode `protobuf:"varint,2,opt,name=Code,json=code,enum=baluba.UploadStatusCode" json:"Code,omitempty"`
	FileName string           `protobuf:"bytes,3,opt,name=FileName,json=fileName" json:"FileName,omitempty"`
}

func (m *UploadStatus) Reset()                    { *m = UploadStatus{} }
func (m *UploadStatus) String() string            { return proto.CompactTextString(m) }
func (*UploadStatus) ProtoMessage()               {}
func (*UploadStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UploadStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UploadStatus) GetCode() UploadStatusCode {
	if m != nil {
		return m.Code
	}
	return UploadStatusCode_Unknown
}

func (m *UploadStatus) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func init() {
	proto.RegisterType((*Chunk)(nil), "baluba.Chunk")
	proto.RegisterType((*Files)(nil), "baluba.Files")
	proto.RegisterType((*UploadStatus)(nil), "baluba.UploadStatus")
	proto.RegisterEnum("baluba.UploadStatusCode", UploadStatusCode_name, UploadStatusCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BalubaService service

type BalubaServiceClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (BalubaService_UploadClient, error)
	Create(ctx context.Context, in *Files, opts ...grpc.CallOption) (*UploadStatus, error)
}

type balubaServiceClient struct {
	cc *grpc.ClientConn
}

func NewBalubaServiceClient(cc *grpc.ClientConn) BalubaServiceClient {
	return &balubaServiceClient{cc}
}

func (c *balubaServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (BalubaService_UploadClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BalubaService_serviceDesc.Streams[0], c.cc, "/baluba.BalubaService/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &balubaServiceUploadClient{stream}
	return x, nil
}

type BalubaService_UploadClient interface {
	Send(*Chunk) error
	Recv() (*UploadStatus, error)
	grpc.ClientStream
}

type balubaServiceUploadClient struct {
	grpc.ClientStream
}

func (x *balubaServiceUploadClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *balubaServiceUploadClient) Recv() (*UploadStatus, error) {
	m := new(UploadStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *balubaServiceClient) Create(ctx context.Context, in *Files, opts ...grpc.CallOption) (*UploadStatus, error) {
	out := new(UploadStatus)
	err := grpc.Invoke(ctx, "/baluba.BalubaService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BalubaService service

type BalubaServiceServer interface {
	Upload(BalubaService_UploadServer) error
	Create(context.Context, *Files) (*UploadStatus, error)
}

func RegisterBalubaServiceServer(s *grpc.Server, srv BalubaServiceServer) {
	s.RegisterService(&_BalubaService_serviceDesc, srv)
}

func _BalubaService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BalubaServiceServer).Upload(&balubaServiceUploadServer{stream})
}

type BalubaService_UploadServer interface {
	Send(*UploadStatus) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type balubaServiceUploadServer struct {
	grpc.ServerStream
}

func (x *balubaServiceUploadServer) Send(m *UploadStatus) error {
	return x.ServerStream.SendMsg(m)
}

func (x *balubaServiceUploadServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BalubaService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Files)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalubaServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/baluba.BalubaService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalubaServiceServer).Create(ctx, req.(*Files))
	}
	return interceptor(ctx, in, info, handler)
}

var _BalubaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "baluba.BalubaService",
	HandlerType: (*BalubaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BalubaService_Create_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _BalubaService_Upload_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "baluba.proto",
}

func init() { proto.RegisterFile("baluba.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x52, 0xd1, 0x6e, 0xe2, 0x30,
	0x10, 0xc4, 0x90, 0x38, 0xb0, 0xc0, 0x29, 0x5a, 0x9d, 0x4e, 0x16, 0xba, 0x87, 0x5c, 0x9e, 0x22,
	0x74, 0xe2, 0x4e, 0xf0, 0x07, 0x87, 0xc4, 0xdb, 0xb5, 0x52, 0x10, 0x1f, 0x60, 0x12, 0xd3, 0x44,
	0x04, 0x1b, 0xc5, 0x0e, 0x55, 0xfb, 0x87, 0xfd, 0xab, 0xca, 0x0e, 0x14, 0x5a, 0xb5, 0x6f, 0x3b,
	0x3b, 0x9a, 0xf1, 0xcc, 0xca, 0x30, 0xda, 0xf2, 0xaa, 0xd9, 0xf2, 0xd9, 0xb1, 0x56, 0x46, 0x21,
	0x6d, 0x51, 0xfc, 0x42, 0xc0, 0x5f, 0x16, 0x8d, 0xdc, 0x23, 0x83, 0x20, 0x53, 0xd2, 0x08, 0x69,
	0x18, 0x89, 0x48, 0x32, 0x4a, 0x2f, 0x10, 0x11, 0x3c, 0xc9, 0x0f, 0x82, 0x75, 0x23, 0x92, 0x0c,
	0x52, 0x37, 0xe3, 0x04, 0xfa, 0x85, 0xd2, 0xc6, 0xed, 0x7b, 0x6e, 0xff, 0x86, 0xf1, 0x27, 0x0c,
	0xf2, 0xb2, 0x16, 0x99, 0x51, 0xf5, 0x13, 0xf3, 0x1c, 0x79, 0x5d, 0x58, 0x37, 0x5d, 0x3e, 0x0b,
	0xe6, 0x47, 0x24, 0xe9, 0xa5, 0x6e, 0xb6, 0x6f, 0x9f, 0x44, 0xad, 0x4b, 0x25, 0x19, 0x8d, 0x48,
	0xe2, 0xa7, 0x17, 0x88, 0x3f, 0x80, 0xf2, 0xcc, 0x58, 0x22, 0x70, 0x46, 0x67, 0x64, 0x5d, 0x0a,
	0xae, 0x0b, 0xd6, 0x6f, 0x33, 0xd9, 0x39, 0x9e, 0x82, 0xbf, 0x2a, 0x2b, 0xa1, 0xf1, 0x17, 0x78,
	0xbb, 0xb2, 0x12, 0x8c, 0x44, 0xbd, 0x64, 0x38, 0x1f, 0xcf, 0xce, 0xcd, 0x5d, 0xcf, 0xd4, 0x51,
	0x71, 0x0d, 0xa3, 0xcd, 0xb1, 0x52, 0x3c, 0x5f, 0x1b, 0x6e, 0x1a, 0x6d, 0x13, 0xfc, 0x17, 0x5a,
	0xf3, 0x07, 0xe1, 0xda, 0x0f, 0xd2, 0xe0, 0xd0, 0x42, 0xfc, 0x0d, 0xde, 0x52, 0xe5, 0x6d, 0xfb,
	0x6f, 0x73, 0x76, 0x31, 0xbb, 0x55, 0x5b, 0x3e, 0xf5, 0x32, 0x95, 0xbb, 0xbb, 0xd8, 0x0c, 0x77,
	0x37, 0x77, 0xd9, 0x9d, 0xf1, 0x74, 0x01, 0xe1, 0x47, 0x15, 0x0e, 0x21, 0xd8, 0xc8, 0xbd, 0x54,
	0x8f, 0x32, 0xec, 0x20, 0x85, 0xee, 0xfd, 0x3e, 0x24, 0x08, 0x40, 0x57, 0xbc, 0xac, 0x44, 0x1e,
	0x76, 0xe7, 0x0d, 0x8c, 0xff, 0xb9, 0x17, 0xd7, 0xa2, 0x3e, 0x95, 0x99, 0xc0, 0x05, 0xd0, 0xd6,
	0x05, 0xdf, 0x17, 0x9b, 0x7c, 0xff, 0x2c, 0x5a, 0xdc, 0x49, 0xc8, 0x5f, 0x82, 0x7f, 0x80, 0x2e,
	0x6b, 0xc1, 0x8d, 0xb8, 0x8a, 0xdc, 0xa9, 0xbe, 0x12, 0x6d, 0xa9, 0xfb, 0x26, 0x8b, 0xd7, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x29, 0x45, 0x28, 0x65, 0x36, 0x02, 0x00, 0x00,
}
